server:
  port: ${PORT:8081}


spring:
  application:
    name: bank-register-client

  datasource:
    url: jdbc:postgresql://localhost:5432/banco_connect_db
    username: jair123
    password: jair123
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

