server:
  port: 8082

spring:
    application:
              name: bank-secure-auth

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


cliente:
      auth: http://localhost:8765/clientes/{email}