# Use a imagem oficial do PostgreSQL como base
FROM postgres:latest

# Defina variáveis de ambiente para configurar o PostgreSQL
ENV POSTGRES_USER=jair123
ENV POSTGRES_PASSWORD=jair123
ENV POSTGRES_DB=banco_connect_db

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432