spring:
  application:
    name: bank-gateway-service

  cloud:
    gateway:
      routes:
        - id: bank-cliente-cadastro
          uri: http://localhost:8081
          predicates:
            - Path=/clientes/**
server:
  port: 8765


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG