server:
  port: 8765

spring:
  application:
    name: bank-gateway-service

  cloud:
    gateway:
      routes:
        - id: bank-cliente-cadastro
          uri: http://localhost:8081
          predicates:
            - Path=/clientes/**
        - id: bank-secure-auth
          uri: http://localhost:8082
          predicates: 
            - Path=/auth/**
          filters:
            - RewriteResponseHeader=Cookie, "REDACTED"
            - RewriteResponseHeader=Set-Cookie, "REDACTED"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG