server:
    port: 8765

spring:
  application:
    name: bank-gateway-service

#  spring:
#    cloud:
#      gateway:
#        routes:
#          - id: bank-cliente-cadastro
#            uri: http://localhost:8081
#            predicates:
#              - Path=/clientes/** | /contas/**
#
#          - id: bank-secure-auth
#            uri: http://localhost:8082
#            predicates:
#              - Path=/auth/clientes/** | /auth/contas/**
#            filters:
#              - RewriteResponseHeader=Cookie, ".*", "REDACTED"
#              - RewriteResponseHeader=Set-Cookie, ".*", "REDACTED"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

