server:
  port: 8765

spring:
  application:
    name: bank-gateway-zull-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    cadastro-cliente:
            service-id: bank-cliente-cadastro
            path: /bank-cliente-cadastro/**